# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pylirc_ui3.ui'
#
# Created: Tue Apr 12 15:10:43 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.video = QtGui.QWidget()
        self.video.setGeometry(QtCore.QRect(0, 0, 782, 382))
        self.video.setObjectName("video")
        self.verticalLayout = QtGui.QVBoxLayout(self.video)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.listWidget_video = QtGui.QListWidget(self.video)
        self.listWidget_video.setMaximumSize(QtCore.QSize(300, 16777215))
        self.listWidget_video.setObjectName("listWidget_video")
        self.horizontalLayout_3.addWidget(self.listWidget_video)
        self.frame_video_wrap = QtGui.QFrame(self.video)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_video_wrap.sizePolicy().hasHeightForWidth())
        self.frame_video_wrap.setSizePolicy(sizePolicy)
        self.frame_video_wrap.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_video_wrap.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_video_wrap.setObjectName("frame_video_wrap")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_video_wrap)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_video = QtGui.QFrame(self.frame_video_wrap)
        self.frame_video.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_video.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_video.setObjectName("frame_video")
        self.verticalLayout_5.addWidget(self.frame_video)
        self.horizontalLayout_3.addWidget(self.frame_video_wrap)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.toolBox.addItem(self.video, "")
        self.tv = QtGui.QWidget()
        self.tv.setGeometry(QtCore.QRect(0, 0, 782, 382))
        self.tv.setObjectName("tv")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tv)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget_tv = QtGui.QListWidget(self.tv)
        self.listWidget_tv.setObjectName("listWidget_tv")
        self.verticalLayout_2.addWidget(self.listWidget_tv)
        self.toolBox.addItem(self.tv, "")
        self.music = QtGui.QWidget()
        self.music.setObjectName("music")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.music)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_music = QtGui.QListWidget(self.music)
        self.listWidget_music.setObjectName("listWidget_music")
        self.verticalLayout_3.addWidget(self.listWidget_music)
        self.toolBox.addItem(self.music, "")
        self.photo = QtGui.QWidget()
        self.photo.setObjectName("photo")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.photo)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget_photo = QtGui.QListWidget(self.photo)
        self.listWidget_photo.setObjectName("listWidget_photo")
        self.verticalLayout_4.addWidget(self.listWidget_photo)
        self.toolBox.addItem(self.photo, "")
        self.gridLayout.addWidget(self.toolBox, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalSlider_video = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider_video.setMaximum(1000)
        self.horizontalSlider_video.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_video.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_video.setTickInterval(100)
        self.horizontalSlider_video.setObjectName("horizontalSlider_video")
        self.gridLayout_2.addWidget(self.horizontalSlider_video, 1, 0, 1, 1)
        self.horizontalSlider_audio = QtGui.QSlider(self.centralwidget)
        self.horizontalSlider_audio.setMaximumSize(QtCore.QSize(100, 16777215))
        self.horizontalSlider_audio.setMaximum(100)
        self.horizontalSlider_audio.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_audio.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_audio.setTickInterval(20)
        self.horizontalSlider_audio.setObjectName("horizontalSlider_audio")
        self.gridLayout_2.addWidget(self.horizontalSlider_audio, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_open = QtGui.QPushButton(self.centralwidget)
        self.pushButton_open.setObjectName("pushButton_open")
        self.horizontalLayout.addWidget(self.pushButton_open)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_play = QtGui.QPushButton(self.centralwidget)
        self.pushButton_play.setObjectName("pushButton_play")
        self.horizontalLayout.addWidget(self.pushButton_play)
        self.pushButton_stop = QtGui.QPushButton(self.centralwidget)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout.addWidget(self.pushButton_stop)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_exit = QtGui.QPushButton(self.centralwidget)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.horizontalLayout.addWidget(self.pushButton_exit)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.video), QtGui.QApplication.translate("MainWindow", "Videozz", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tv), QtGui.QApplication.translate("MainWindow", "TVzz", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.music), QtGui.QApplication.translate("MainWindow", "Muzza", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.photo), QtGui.QApplication.translate("MainWindow", "Photozz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Volume", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_open.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_play.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

