'''
Created on Apr 12, 2011

@author: hinko
'''

class Remote():

    def __init__(self, remote_name = 'unknown', prog_name = 'pylirc'):
        self.remote_name = remote_name
        self.prog_name = prog_name
        self.buttons = None

    def set_keys(self, keys):
        self.buttons = keys

    def generate_conf(self, conf_file):
        f = open(conf_file, "w+")
        hdr = "# Generated by Remote.generate_conf()\n\n"
        f.write(hdr)
        for (k, v) in self.buttons.items():
            key = "begin\n"
            key += " remote = %s\n" % self.remote_name
            key += " button = %s\n" % v
            key += " prog   = %s\n" % self.prog_name
            key += " config = %s\n" % k
            key += "end\n"
            key += "\n"
            f.write(key)
        f.close()

remotePC = dict({
"power"        : "POWER",
"radio"        : "RADIO",
"tv"           : "TV",
"dvd"          : "DVD",
"music"        : "MUSIC",
"photo"        : "PHOTO",
"video"        : "VIDEO",
"home"         : "DVD_MENU",
"mute"         : "MUTE",
"back"         : "BACK",
"guide"        : "GUIDE",
"more"         : "",
"volume_up"    : "VOLUME_UP",
"volume_down"  : "VOLUME_DOWN",
"channel_up"   : "CHANNEL_UP",
"channel_down" : "CHANNEL_DOWN",
"up"           : "ARROW_UP",
"down"         : "ARROW_DOWN",
"left"         : "ARROW_LEFT",
"right"        : "ARROW_RIGHT",
"ok"           : "",
"enter"        : "ENTER",
"clear"        : "",
"record"       : "RECORD",
"repeat"       : "REPEAT",
"play"         : "PLAY",
"pause"        : "PAUSE",
"stop"         : "STOP",
"rewind"       : "REWIND",
"forward"      : "FORWARD",
"prev_track"   : "PREV_TRACK",
"next_track"   : "NEXT_TRACK",
"0"            : "NUMPAD_0",
"1"            : "NUMPAD_1",
"2"            : "NUMPAD_2",
"3"            : "NUMPAD_3",
"4"            : "NUMPAD_4",
"5"            : "NUMPAD_5",
"6"            : "NUMPAD_6",
"7"            : "NUMPAD_7",
"8"            : "NUMPAD_8",
"9"            : "NUMPAD_9",
"star"         : "",
"hash"         : "",
"fullscreen"   : "Aspect",
"teletext"     : "",
"blue"         : "",
"yellow"       : "",
"green"        : "",
"red"          : "",
})


remoteTV = dict({
"power"        : "Power",
"radio"        : "Radio",
"tv"           : "LiveTV",
"dvd"          : "DVD",
"music"        : "Music",
"photo"        : "Pictures",
"video"        : "Videos",
"home"         : "Home",
"mute"         : "Mute",
"back"         : "Back",
"guide"        : "Guide",
"more"         : "More",
"volume_up"    : "VolUp",
"volume_down"  : "VolDown",
"channel_up"   : "ChanUp",
"channel_down" : "ChanDown",
"up"           : "Up",
"down"         : "Down",
"left"         : "Left",
"right"        : "Right",
"ok"           : "OK",
"enter"        : "Enter",
"clear"        : "Clear",
"record"       : "Record",
"repeat"       : "",
"play"         : "Play",
"pause"        : "Pause",
"stop"         : "Stop",
"rewind"       : "Rewind",
"forward"      : "Forward",
"prev_track"   : "Replay",
"next_track"   : "Skip",
"0"            : "Zero",
"1"            : "One",
"2"            : "Two",
"3"            : "Three",
"4"            : "Four",
"5"            : "Five",
"6"            : "Six",
"7"            : "Seven",
"8"            : "Eight",
"9"            : "Nine",
"star"         : "Star",
"hash"         : "Hash",
"fullscreen"   : "Aspect",
"teletext"     : "Teletext",
"blue"         : "Blue",
"yellow"       : "Yellow",
"green"        : "Green",
"red"          : "Red",

})

if __name__ == '__main__':
    for (k, v) in remoteTV.items():
        #print k, v
        if k not in remotePC:
            print "remotePC: \"%s\": \"%s\"," % (k, v)
    for (k, v) in remotePC.items():
        #print k, v
        if k not in remoteTV:
            print "remoteTV: \"%s\": \"%s\"," % (k, v)

    rpc = Remote('Cyp_Se_WitheHome')
    rpc.set_keys(remotePC)
    rpc.generate_conf("pylirc.conf.Cyp_Se_WitheHome")

    rtv = Remote('mceusb')
    rtv.set_keys(remoteTV)
    rtv.generate_conf("pylirc.conf.mceusb")
